### ISSUE TITLE
Is it possible to force array/string max size?

### ISSUE THREAD

**Issue by vhbit** [jsgf/rust-xdr#1]
It seems that using `string name<64>` is parsed without any error, but generated code behaves exactly like `string name<>`, i.e. doesn't check actual len.

Are there any plans to implement that?

**Comment by jsgf** [comment]
Good question. <n> doesn't change the encoded representation vs <>, so in a sense they're identical. The only real question is what happens if you try to encode or decode something that exceeds the limit. I guess the options are return an error, or truncate to the limit. I'd probably prefer the former.

What's your use case?

**Comment by jsgf** [comment]
I just pushed a change to implement this, which returns InvalidLen for oversized strings and arrays (largely untested).

**Comment by vhbit** [comment]
Sorry for a delay.

Yep, to have an error is a better way to handle situation. And in my use case (protocol which uses XDR to transfer through wire) I'm more interested in checking input than output. 

It would be also great to have some kind of "error message" where exactly error occurred (for example, name of field/structure being unpacked), but I'm not sure if that can be achieved easily.

I hope to get some time on weekend to check how the new implementation works.

**Comment by jsgf** [comment]
Yeah, it would be good to improve the quality of the error returns.

**Comment by jsgf** [comment]
The current implementation unpacks from the stream before checking the size, so it still allows for memory consumption denial of service. It would be better to check the size before unpacking anything.

**Comment by druzac** [comment]
hmmm... having some issues with this change.
the following xdr spec:
```
struct opaque_auth {
   int flavor;
   opaque body<400>;
};
```
produces:
```
#[derive(Debug, Eq, PartialEq, Clone)]
pub struct opaque_auth {
    pub flavor: i32,
    pub body: Vec<u8>,
}

impl <Out: xdr_codec::Write> xdr_codec::Pack<Out> for opaque_auth {
    fn pack(&self, out: &mut Out) -> xdr_codec::Result<usize> {
        Ok(try!(self . flavor . pack ( out )) +
               if self.body.len() > 400i64 {
                   return Err(xdr_codec::Error::invalidlen())
               } else { try!(self . body . pack ( out )) } + 0)
    }
}

impl <In: xdr_codec::Read> xdr_codec::Unpack<In> for opaque_auth {
    fn unpack(input: &mut In) -> xdr_codec::Result<(opaque_auth, usize)> {
        let mut sz = 0;
        Ok((opaque_auth{flavor:
                            {
                                let (v, fsz) =
                                    try!(xdr_codec:: Unpack:: unpack ( input
                                         ));
                                sz += fsz;
                                v
                            },
                        body:
                            {
                                let (v, fsz) =
                                    {
                                        let (v, sz) =
                                            try!(xdr_codec:: Unpack:: unpack (
                                                 input ));
                                        if v.len() > 400i64 {
                                            return Err(xdr_codec::Error::invalidlen())
                                        } else { (v, sz) }
                                    };
                                sz += fsz;
                                v
                            },}, sz))
    }
}
```
which the compiler complains about:
```
bounded_flex_xdr.rs:18:37: 18:43 error: mismatched types:
 expected `usize`,
    found `i64`
(expected usize,
    found i64) [E0308]
bounded_flex_xdr.rs:18                if self.body.len() > 400i64 {
bounded_flex.rs:8:5: 8:37 note: in this expansion of include!
bounded_flex_xdr.rs:18:37: 18:43 help: run `rustc --explain E0308` to see a detailed explanation
bounded_flex_xdr.rs:42:44: 42:51 error: the type of this value must be known in this context
bounded_flex_xdr.rs:42                                         if v.len() > 400i64 {
```

**Comment by jsgf** [comment]
I pushed a fix for this.
