### ISSUE TITLE
Recent nightly errors

### ISSUE THREAD

**Issue by icorderi** [jsgf/rust-xdr#10]
Jeremy, seems there were some breaking AST changes in recent nightlies. 

.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/rustast.rs:6:40: 6:49 error: unresolved import `syntax::ast::TokenTree`. **There is no `TokenTree` in `syntax::ast`** [E0432]
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/rustast.rs:6 pub use syntax::ast::{Mod, Item, Expr, TokenTree, Ident};
                                                                                                                                         ^~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/rustast.rs:6:40: 6:49 help: run `rustc --explain E0432` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/fake_extctxt.rs:4:5: 4:39 error: unresolved import `syntax::feature_gate::GatedCfgAttr`. **There is no `GatedCfgAttr` in `syntax::feature_gate`**. Did you mean to use `GatedCfg`? [E0432]
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/fake_extctxt.rs:4 use syntax::feature_gate::GatedCfgAttr;
                                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/fake_extctxt.rs:4:5: 4:39 help: run `rustc --explain E0432` to see a detailed explanation
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/fake_extctxt.rs:9:7: 9:17 error: the trait bound `syntax::ext::base::MacroLoader: std::marker::Sized` is not satisfied [E0277]
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/fake_extctxt.rs:9   let mut fg_cfg = Vec::<GatedCfgAttr>::new();
                                                                                                             ^~~~~~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/fake_extctxt.rs:9:7: 9:17 help: run `rustc --explain E0277` to see a detailed explanation

##### The rest might be related to those two missing types. 

.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/fake_extctxt.rs:9:7: 9:17 note: `syntax::ext::base::MacroLoader` does not have a constant size known at compile-time
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/fake_extctxt.rs:9:7: 9:17 note: all local variables must have a statically known size
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:257:39: 257:45 error: the type of this value must be known in this context
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:257                     let mut buf: [u8; $value as usize] = unsafe { mem::uninitialized() };
                                                                                                                                      ^~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:255:17: 260:19 note: in this expansion of quote_tokens!
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:322:52: 322:56 error: the type of this value must be known in this context
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:322                     quote_tokens!(ctxt, Option<Box<$tok>>)
                                                                                                                                                   ^~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:322:21: 322:59 note: in this expansion of quote_tokens!
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:396:51: 396:55 error: the type of this value must be known in this context
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:396                     tok = quote_tokens!(ctxt, Box<$tok>)
                                                                                                                                                  ^~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:396:27: 396:57 note: in this expansion of quote_tokens!
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:468:47: 468:51 error: the type of this value must be known in this context
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:468         Ok(quote_item!(ctxt, pub type $name = $tok;).unwrap())
                                                                                                                                              ^~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:468:12: 468:53 note: in this expansion of quote_item!
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:502:68: 502:74 error: the type of this value must be known in this context
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:502                                            quote_tokens!(ctxt, pub $field: $ty,)))));
                                                                                                                                                                   ^~~~~~
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:502:44: 502:81 note: in this expansion of quote_tokens!
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:498:37: 502:85 note: in this expansion of try! (defined in <std macros>)
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:763:64: 763:71 error: the type of this value must be known in this context
.cargo/registry/src/github.com-1ecc6299db9ec823/xdrgen-0.2.4/src/spec/mod.rs:763                                       $field: { let (v, fsz) = $unpack; sz += fsz; v },)

**Comment by jsgf** [comment]
Thanks, I've just pushed a fix.
