### ISSUE TITLE
rust-xdr on stable

### ISSUE THREAD

**Issue by icorderi** [jsgf/rust-xdr#14]
@jsgf, with **rust 1.15** out supporting **macros 1.1** on stable, could we move this crate to stable too? Or are you still missing key features on the stable procedural macros to get it to work?

**Comment by jsgf** [comment]
The main dependency is on using syntax for code generation - it looks like everyone is moving to the `quote` crate (such as https://github.com/kevinmehall/rust-peg/commit/10b3535a24c143ec28e0d7ab5d2d8217e7a34ba6), which depends on macros 1.1 so should be stable on 1.15.

**Comment by icorderi** [comment]
Yea, `quote` is on the official [docs](https://doc.rust-lang.org/book/procedural-macros.html) for **proc macros**.

**Comment by jsgf** [comment]
In progress - check out master

**Comment by jsgf** [comment]
0.4 should work on stable. Please tell me if you see regressions.
