### ISSUE TITLE
Derives for u8

### ISSUE THREAD

**Issue by polachok** [jsgf/rust-xdr#22]
test.x
```
struct test {
	unsigned char x;
};
```

Structs containing char fields don't implement Copy, Clone, Debug, etc.
```
// GENERATED CODE
//
// Generated from test.x by xdrgen.
//
// DO NOT EDIT


pub struct test { pub x : u8 , }

impl < Out : xdr_codec :: Write > xdr_codec :: Pack < Out > for test { fn pack ( & self , out : & mut Out ) -> xdr_codec :: Result < usize > { Ok ( self . x . pack ( out ) ? + 0 ) } }

impl < In : xdr_codec :: Read > xdr_codec :: Unpack < In > for test { fn unpack ( input : & mut In ) -> xdr_codec :: Result < ( test , usize ) > { let mut sz = 0 ; Ok ( ( test { x : { let ( v , fsz ) = xdr_codec :: Unpack :: unpack ( input ) ? ; sz += fsz ; v } , } , sz ) ) } }
```

**Comment by jsgf** [comment]
Support for `unsigned char` is a bit of a hack. XDR doesn't directly support the type `unsigned char` as a type, but xdrgen has a parse-time hack that makes it treat it as an alias for the type name `u8`. However this is just treated as a `Type::ident` - ie, like a typedef - that xdrgen has no other knowledge about, such as what traits can be derived.

Adding derive support for `unsigned char` would need more complexity, such as attaching derivable attributes to a `Type::ident`. I'll think about it.

**Comment by jsgf** [comment]
Does this fix it for you?

**Comment by polachok** [comment]
Yes, thanks
