### ISSUE TITLE
xdr short issue

### ISSUE THREAD

**Issue by polachok** [jsgf/rust-xdr#23]
I couldn't find short in XDR RFC (https://tools.ietf.org/html/rfc4506.html), but it looks like it is used in the wild (https://libvirt.org/git/?p=libvirt.git;a=blob_plain;f=src/remote/remote_protocol.x;hb=HEAD).
glibc implements it (https://github.com/lattera/glibc/blob/a2f34833b1042d5d8eeb263b4cf4caaea138c4ad/sunrpc/xdr.c#L369) same way as long. 
Would you be willing to support it (maybe hidden under feature flag)?

**Comment by jsgf** [comment]
Does this fix it for you?

**Comment by polachok** [comment]
I expected it to be i16/u16, but whatever works, thanks! Can you please bump version?

**Comment by jsgf** [comment]
I considered it but it raises other questions like what if the on-wire u32 has values that don't fit into u16, etc.
