### ISSUE TITLE
update to nom ^3.0

### ISSUE THREAD

**Issue by icorderi** [jsgf/rust-xdr#26]
@jsgf, could you take a look at updating nom? 
The old `regex` dependencies are causing some issues with compilation.

**Comment by jsgf** [comment]
I'll try to get to it in a couple of days. Nom 3 drops `chain!` so all those will need to be reworked, but I just did it with another parser and it wasn't too bad.

**Comment by icorderi** [comment]
Yea I saw it was involved which is why I left it out of the other PR. 
No rush, thanks!

**Comment by jsgf** [comment]
Done.
