### ISSUE TITLE
Multiple `long` definitions

### ISSUE THREAD

**Issue by icorderi** [jsgf/rust-xdr#9]
Projects with multiple `*.x` files don't build due to duplicated `long` definitions.

```sh
../out/xdr-1.rs:269 pub type long = i32;                                                                                                          ^~~~~~~~~~~~~~~~~~~~
../out/xdr-2.rs:98:1: 98:21 note: previous definition of `long` here
../out/xdr-2.rs:98 pub type long = i32;
```

**Comment by jsgf** [comment]
Yeah, the "auto-define long if the .x doesn't use it" thing is backfiring here. I think the simple thing to do is make `long` an actual keyword that's the same as `int`. That's not RFC compliant, but I doubt any real .x is using `long` to mean anything else since `rpcgen` treats it like a keyword.

**Comment by jsgf** [comment]
I pushed an update that just treats long as a keyword rather than making an alias for it.

**Comment by icorderi** [comment]
Great! It builds now. 
You can update `crates.io`

**Comment by jsgf** [comment]
OK, done
